---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nocastra/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r out/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;