---
deployment:
  tasks:
    - export DEPLOYPATH=/home/nocastra/public_html/
    - cd /home/nocastra/repositories/Nocastra-Website
    - npm run build
    - /bin/cp -r out/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    - /bin/rm -rf $DEPLOYPATH/.git
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
